### ISSUE TITLE
Good URLs throughout

### ISSUE THREAD

**Issue by buckett** [ox-it/orgchart#3]
Would be nice if rather than just the pages of the app having URLs the current state of the app had a good URL as well so I could send someone a like to the person.

**Comment by alexsdutton** [comment]
I've done this for the existing pages, so I'll close this. See e.g. https://inside.it.ox.ac.uk/organization-chart or https://inside.it.ox.ac.uk/people/photo-board.

I should still create pages for individual people and teams though, so I'll create a new issue for that.
